name: SatsBuddy

options:
  xcodeVersion: "16.3"
  deploymentTarget:
    iOS: "18.5"
  defaultConfig: Release

configs:
  Debug: debug
  Release: release

settings:
  configs:
    Debug:
      xcconfig: Configs/Debug.xcconfig
    Release:
      xcconfig: Configs/Release.xcconfig

packages:
  bdk-swift:
    url: https://github.com/bitcoindevkit/bdk-swift
    exactVersion: "2.3.1"
  rust-cktap:
    url: https://github.com/bitcoindevkit/rust-cktap
    exactVersion: "0.2.2"
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    exactVersion: "4.2.2"
  BitcoinUI:
    url: https://github.com/reez/BitcoinUI
    branch: main
  CodeScanner:
    url: https://github.com/twostraws/CodeScanner.git
    exactVersion: "2.5.2"

targets:
  SatsBuddy:
    type: application
    platform: iOS
    configFiles:
      Debug: Configs/SatsBuddy.xcconfig
      Release: Configs/SatsBuddy.xcconfig
    sources:
      - path: SatsBuddy
        excludes:
          - Info.plist
    resources:
      - path: README.md
    dependencies:
      - package: bdk-swift
        product: BitcoinDevKit
      - package: rust-cktap
        product: CKTap
      - package: KeychainAccess
      - package: BitcoinUI
      - package: CodeScanner

  SatsBuddyTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SatsBuddyTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.reez.SatsBuddyTests
    dependencies:
      - target: SatsBuddy

schemes:
  SatsBuddy:
    build:
      targets:
        SatsBuddy: all
        SatsBuddyTests: [test]
    test:
      targets:
        - SatsBuddyTests
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
